// export const INPUT_CHANGE = "INPUT_CHANGE";
export const FETCH_CONTACTS_REQUEST = "FETCH_CONTACTS_REQUEST";
export const FETCH_CONTACTS_SUCCESS = "FETCH_CONTACTS_SUCCESS";

export const FILTER_CONTACTS_SUCCESS = "FILTER_CONTACTS_SUCCESS";
export const TEXT_REMOVE_CARD = "TEXT_REMOVE_CARD";
